/*
 * PinConfig.h
 *
 *  Created on: Jan 25, 2021
 *      Author: Vaibhav Bansal
 */

#ifndef INC_PINCONFIG_H_
#define INC_PINCONFIG_H_

#include "stm32g0xx_hal.h"

#define SEGMENT7_A1_PORT		GPIOB
#define SEGMENT7_A1_PIN 		GPIO_PIN_0

#define SEGMENT7_B1_PORT		GPIOB
#define SEGMENT7_B1_PIN 		GPIO_PIN_1

#define SEGMENT7_C1_PORT		GPIOB
#define SEGMENT7_C1_PIN 		GPIO_PIN_2

#define SEGMENT7_D1_PORT		GPIOB
#define SEGMENT7_D1_PIN 		GPIO_PIN_10

#define SEGMENT7_E1_PORT		GPIOB
#define SEGMENT7_E1_PIN			GPIO_PIN_11

#define SEGMENT7_F1_PORT		GPIOB
#define SEGMENT7_F1_PIN			GPIO_PIN_12

#define SEGMENT7_G1_PORT		GPIOB
#define SEGMENT7_G1_PIN			GPIO_PIN_13

#define SEGMENT7_H1_PORT		GPIOB
#define SEGMENT7_H1_PIN     	GPIO_PIN_14

#define SEGMENT7_DIGIT1_PORT	GPIOB
#define SEGMENT7_DIGIT1_PIN 	GPIO_PIN_15

#define SEGMENT7_DIGIT2_PORT	GPIOA
#define SEGMENT7_DIGIT2_PIN 	GPIO_PIN_8

#define SEGMENT7_DIGIT3_PORT	GPIOC
#define SEGMENT7_DIGIT3_PIN 	GPIO_PIN_6

#define SEGMENT7_DIGIT4_PORT	GPIOC
#define SEGMENT7_DIGIT4_PIN 	GPIO_PIN_7

#define DISPLAY_DP_PORT			GPIOA
#define DISPLAY_DP_PIN			GPIO_PIN_12

#endif /* INC_PINCONFIG_H_ */
